# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{protobuf_spec}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Busbey"]
  s.date = %q{2012-04-30}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{support@connamara.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/equivalence.feature",
    "features/paths.feature",
    "features/step_definitions/steps.rb",
    "features/support/env.rb",
    "features/support/sample.pb.rb",
    "lib/protobuf_spec.rb",
    "lib/protobuf_spec/cucumber.rb",
    "lib/protobuf_spec/matchers.rb",
    "lib/protobuf_spec/matchers/be_protobuf_eql.rb",
    "sample.proto",
    "spec/protobuf_spec/matchers/be_protobuf_eql_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/sample.pb.rb"
  ]
  s.homepage = %q{git://git.connamara.com/protobuf_spec.git}
  s.licenses = ["Connamara"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{TODO: one-line summary of your gem}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

